on: pull_request
name: PHPStan

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          installComposer: 0
          phpstanVersion: ^0.12
          level: 5
          paths: src tests
          configPath: custom-phpstan-config.neon
          useBundled: 1
          arguments: --autoload-file my-custom-autoload.php